---
- name: Deploy Operators
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install GitOps Operator
      include_role:
        name: install_gitops_operator

    - name: Install Pipelines Operator
      include_role:
        name: install_pipelines_operator

    - name: Deploy Demo Apps
      include_role:
        name: deploy_example_apps
...
