---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-ci
  namespace: openshift-gitops
spec:
  project: ocp4-devops-demo
  source:
    repoURL: https://github.com/SkylarScaling/ocp4-devops-demo.git
    targetRevision: HEAD
    path: apps/sample-app-ci
  destination:
    # Need to get this automagically via detection
    server: https://kubernetes.default.svc
    namespace: sample-app-ci
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
...
