apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-clone-output
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: gp2-csi
  resources:
    requests:
      storage: 1Gi
